/**
 * 产品审核系统 - 模拟数据和服务
 */

import type { ProductCategory, Product, ApprovalTask, User } from '../types';

/**
 * 模拟用户数据
 */
export const mockUsers: User[] = [
  { id: '1', username: 'wangwu', name: '王五', role: 'localization', approvalStages: ['本地化'] },
  { id: '2', username: 'zhaoliu', name: '赵六', role: 'legal', approvalStages: ['法务'] },
  { id: '3', username: 'qianqi', name: '钱七', role: 'rsa', approvalStages: ['RSA'] },
  { id: '4', username: 'zhangsan', name: '张三', role: 'submitter' },
  { id: '5', username: 'lisi', name: '李四', role: 'submitter' },
];

/**
 * 模拟产品分类数据
 */
export const mockCategories: ProductCategory[] = [
  {
    id: 1,
    name: '游戏',
    nameEn: 'Games',
    riskLevel: 5,
    hasWhitelist: true,
    needLegalReview: true,
    needRsaApproval: false,
    createdAt: '2024-01-01 10:00:00',
    updatedAt: '2024-01-01 10:00:00',
    editor: 'admin',
    creator: 'admin',
  },
  {
    id: 2,
    name: '工具',
    nameEn: 'Tools',
    riskLevel: 2,
    hasWhitelist: true,
    needLegalReview: false,
    needRsaApproval: false,
    createdAt: '2024-01-02 10:00:00',
    updatedAt: '2024-01-02 10:00:00',
    editor: 'admin',
    creator: 'admin',
  },
  {
    id: 3,
    name: '社交',
    nameEn: 'Social',
    riskLevel: 7,
    hasWhitelist: true,
    needLegalReview: true,
    needRsaApproval: true,
    createdAt: '2024-01-03 10:00:00',
    updatedAt: '2024-01-03 10:00:00',
    editor: 'admin',
    creator: 'admin',
  },
  {
    id: 4,
    name: '金融',
    nameEn: 'Finance',
    riskLevel: 9,
    hasWhitelist: true,
    needLegalReview: true,
    needRsaApproval: true,
    createdAt: '2024-01-04 10:00:00',
    updatedAt: '2024-01-04 10:00:00',
    editor: 'admin',
    creator: 'admin',
  },
];

/**
 * 模拟产品数据
 */
export const mockProducts: Product[] = [
  {
    id: 1,
    packageName: 'com.example.game1',
    industry: 'GAME_ACTION',
    developer: 'Example Developer',
    packageSize: '100MB',
    targetCountries: ['CN', 'US', 'JP'],
    shelfStatus: 'BOTH',
    gaLink: 'https://play.google.com/store/apps/details?id=com.example.game1',
    gpLink: 'https://play.google.com/store/apps/details?id=com.example.game1',
    gpRating: 4.5,
    attributionWindow: 7,
    settlementMethod: 'CPS',
    submitter: '张三',
    submitTime: '2024-01-01 10:00:00',
    approvalStatus: 'pending',
    categoryId: 1,
    approvalFlow: [],
  },
  {
    id: 2,
    packageName: 'com.example.app1',
    industry: 'APP_TOOLS',
    developer: 'Another Developer',
    packageSize: '50MB',
    targetCountries: ['CN', 'US'],
    shelfStatus: 'GA',
    gaLink: 'https://play.google.com/store/apps/details?id=com.example.app1',
    gpLink: '',
    gpRating: 4.0,
    attributionWindow: 30,
    settlementMethod: 'CPA',
    submitter: '李四',
    submitTime: '2024-01-02 10:00:00',
    approvalStatus: 'approving',
    categoryId: 2,
    approvalFlow: [
      {
        stage: '本地化',
        approver: '王五',
        result: 'approved',
        time: '2024-01-02 11:00:00',
        comment: '通过',
      },
      {
        stage: '法务',
        approver: '赵六',
        result: 'pending',
        time: '',
        comment: '',
      },
    ],
  },
  {
    id: 3,
    packageName: 'com.example.social1',
    industry: 'APP_SOCIAL',
    developer: 'Social Developer',
    packageSize: '80MB',
    targetCountries: ['CN', 'US', 'JP', 'KR'],
    shelfStatus: 'BOTH',
    gaLink: 'https://play.google.com/store/apps/details?id=com.example.social1',
    gpLink: 'https://play.google.com/store/apps/details?id=com.example.social1',
    gpRating: 4.8,
    attributionWindow: 14,
    settlementMethod: 'CPE',
    submitter: '张三',
    submitTime: '2024-01-03 10:00:00',
    approvalStatus: 'approved',
    categoryId: 3,
    approvalFlow: [
      {
        stage: '本地化',
        approver: '王五',
        result: 'approved',
        time: '2024-01-03 11:00:00',
        comment: '通过',
      },
      {
        stage: '法务',
        approver: '赵六',
        result: 'approved',
        time: '2024-01-03 14:00:00',
        comment: '通过',
      },
      {
        stage: 'RSA',
        approver: '钱七',
        result: 'approved',
        time: '2024-01-03 16:00:00',
        comment: '通过',
      },
    ],
  },
  {
    id: 4,
    packageName: 'com.example.finance1',
    industry: 'APP_FINANCE',
    developer: 'Finance Developer',
    packageSize: '60MB',
    targetCountries: ['CN'],
    shelfStatus: 'GP',
    gaLink: '',
    gpLink: 'https://play.google.com/store/apps/details?id=com.example.finance1',
    gpRating: 3.5,
    attributionWindow: 30,
    settlementMethod: 'CPP',
    submitter: '李四',
    submitTime: '2024-01-04 10:00:00',
    approvalStatus: 'rejected',
    categoryId: 4,
    approvalFlow: [
      {
        stage: '本地化',
        approver: '王五',
        result: 'approved',
        time: '2024-01-04 11:00:00',
        comment: '通过',
      },
      {
        stage: '法务',
        approver: '赵六',
        result: 'rejected',
        time: '2024-01-04 14:00:00',
        comment: '存在合规问题',
      },
    ],
  },
];

/**
 * 模拟审批任务数据
 */
export const mockApprovalTasks: ApprovalTask[] = [
  {
    id: 1,
    productId: 2,
    package: 'com.example.app1',
    industry: 'APP_TOOLS',
    developer: 'Another Developer',
    submitter: '李四',
    submitTime: '2024-01-02 10:00:00',
    currentStage: '法务',
    approvalStatus: 'approving',
    approvalFlow: [
      {
        stage: '本地化',
        approver: '王五',
        result: 'approved',
        time: '2024-01-02 11:00:00',
        comment: '通过',
      },
      {
        stage: '法务',
        approver: '赵六',
        result: 'pending',
        time: '',
        comment: '',
      },
    ],
  },
];

/**
 * Google Play 行业分类
 */
export const industryOptions = [
  { value: 'GAME_ACTION', label: '游戏 - 动作' },
  { value: 'GAME_ADVENTURE', label: '游戏 - 冒险' },
  { value: 'GAME_ARCADE', label: '游戏 - 街机' },
  { value: 'GAME_BOARD', label: '游戏 - 桌面' },
  { value: 'GAME_CARD', label: '游戏 - 卡牌' },
  { value: 'GAME_CASINO', label: '游戏 - 赌场' },
  { value: 'GAME_CASUAL', label: '游戏 - 休闲' },
  { value: 'GAME_EDUCATIONAL', label: '游戏 - 教育' },
  { value: 'GAME_MUSIC', label: '游戏 - 音乐' },
  { value: 'GAME_PUZZLE', label: '游戏 - 益智' },
  { value: 'GAME_RACING', label: '游戏 - 竞速' },
  { value: 'GAME_ROLE_PLAYING', label: '游戏 - 角色扮演' },
  { value: 'GAME_SIMULATION', label: '游戏 - 模拟' },
  { value: 'GAME_SPORTS', label: '游戏 - 体育' },
  { value: 'GAME_STRATEGY', label: '游戏 - 策略' },
  { value: 'GAME_TRIVIA', label: '游戏 - trivia' },
  { value: 'GAME_WORD', label: '游戏 - 文字' },
  { value: 'APP_BUSINESS', label: '应用 - 商务' },
  { value: 'APP_EDUCATION', label: '应用 - 教育' },
  { value: 'APP_ENTERTAINMENT', label: '应用 - 娱乐' },
  { value: 'APP_FINANCE', label: '应用 - 金融' },
  { value: 'APP_HEALTH_AND_FITNESS', label: '应用 - 健康与健身' },
  { value: 'APP_LIFESTYLE', label: '应用 - 生活方式' },
  { value: 'APP_MEDIA_AND_VIDEO', label: '应用 - 媒体与视频' },
  { value: 'APP_MUSIC_AND_AUDIO', label: '应用 - 音乐与音频' },
  { value: 'APP_NEWS_AND_MAGAZINES', label: '应用 - 新闻与杂志' },
  { value: 'APP_PERSONALIZATION', label: '应用 - 个性化' },
  { value: 'APP_PHOTOGRAPHY', label: '应用 - 摄影' },
  { value: 'APP_PRODUCTIVITY', label: '应用 - 生产力' },
  { value: 'APP_SHOPPING', label: '应用 - 购物' },
  { value: 'APP_SOCIAL', label: '应用 - 社交' },
  { value: 'APP_TOOLS', label: '应用 - 工具' },
  { value: 'APP_TRAVEL_AND_LOCAL', label: '应用 - 旅行与本地' },
  { value: 'APP_UTILITIES', label: '应用 - 实用工具' },
];

/**
 * 国家代码及中文名
 */
export const countryOptions = [
  { value: 'AD', label: '安道尔' },
  { value: 'AE', label: '阿联酋' },
  { value: 'AF', label: '阿富汗' },
  { value: 'AG', label: '安提瓜和巴布达' },
  { value: 'AI', label: '安圭拉' },
  { value: 'AL', label: '阿尔巴尼亚' },
  { value: 'AM', label: '亚美尼亚' },
  { value: 'AO', label: '安哥拉' },
  { value: 'AQ', label: '南极洲' },
  { value: 'AR', label: '阿根廷' },
  { value: 'AS', label: '美属萨摩亚' },
  { value: 'AT', label: '奥地利' },
  { value: 'AU', label: '澳大利亚' },
  { value: 'AW', label: '阿鲁巴' },
  { value: 'AX', label: '芬兰属地' },
  { value: 'AZ', label: '阿塞拜疆' },
  { value: 'BA', label: '波黑' },
  { value: 'BB', label: '巴巴多斯' },
  { value: 'BD', label: '孟加拉国' },
  { value: 'BE', label: '比利时' },
  { value: 'BF', label: '布基纳法索' },
  { value: 'BG', label: '保加利亚' },
  { value: 'BH', label: '巴林' },
  { value: 'BI', label: '布隆迪' },
  { value: 'BJ', label: '贝宁' },
  { value: 'BL', label: '圣巴泰勒米' },
  { value: 'BM', label: '百慕大' },
  { value: 'BN', label: '文莱' },
  { value: 'BO', label: '玻利维亚' },
  { value: 'BQ', label: '荷属加勒比区' },
  { value: 'BR', label: '巴西' },
  { value: 'BS', label: '巴哈马' },
  { value: 'BT', label: '不丹' },
  { value: 'BV', label: '布韦岛' },
  { value: 'BW', label: '博茨瓦纳' },
  { value: 'BY', label: '白俄罗斯' },
  { value: 'BZ', label: '伯利兹' },
  { value: 'CA', label: '加拿大' },
  { value: 'CC', label: '科科斯(基林)群岛' },
  { value: 'CD', label: '刚果民主共和国' },
  { value: 'CF', label: '中非共和国' },
  { value: 'CG', label: '刚果共和国' },
  { value: 'CH', label: '瑞士' },
  { value: 'CI', label: '科特迪瓦' },
  { value: 'CK', label: '库克群岛' },
  { value: 'CL', label: '智利' },
  { value: 'CM', label: '喀麦隆' },
  { value: 'CN', label: '中国' },
  { value: 'CO', label: '哥伦比亚' },
  { value: 'CR', label: '哥斯达黎加' },
  { value: 'CU', label: '古巴' },
  { value: 'CV', label: '佛得角' },
  { value: 'CW', label: '库拉索' },
  { value: 'CX', label: '圣诞岛' },
  { value: 'CY', label: '塞浦路斯' },
  { value: 'CZ', label: '捷克' },
  { value: 'DE', label: '德国' },
  { value: 'DJ', label: '吉布提' },
  { value: 'DK', label: '丹麦' },
  { value: 'DM', label: '多米尼克' },
  { value: 'DO', label: '多米尼加共和国' },
  { value: 'DZ', label: '阿尔及利亚' },
  { value: 'EC', label: '厄瓜多尔' },
  { value: 'EE', label: '爱沙尼亚' },
  { value: 'EG', label: '埃及' },
  { value: 'EH', label: '西撒哈拉' },
  { value: 'ER', label: '厄立特里亚' },
  { value: 'ES', label: '西班牙' },
  { value: 'ET', label: '埃塞俄比亚' },
  { value: 'FI', label: '芬兰' },
  { value: 'FJ', label: '斐济' },
  { value: 'FK', label: '福克兰群岛' },
  { value: 'FM', label: '密克罗尼西亚' },
  { value: 'FO', label: '法罗群岛' },
  { value: 'FR', label: '法国' },
  { value: 'GA', label: '加蓬' },
  { value: 'GB', label: '英国' },
  { value: 'GD', label: '格林纳达' },
  { value: 'GE', label: '格鲁吉亚' },
  { value: 'GF', label: '法属圭亚那' },
  { value: 'GG', label: '根西岛' },
  { value: 'GH', label: '加纳' },
  { value: 'GI', label: '直布罗陀' },
  { value: 'GL', label: '格陵兰' },
  { value: 'GM', label: '冈比亚' },
  { value: 'GN', label: '几内亚' },
  { value: 'GP', label: '瓜德罗普' },
  { value: 'GQ', label: '赤道几内亚' },
  { value: 'GR', label: '希腊' },
  { value: 'GS', label: '南格鲁吉亚和南桑威奇群岛' },
  { value: 'GT', label: '危地马拉' },
  { value: 'GU', label: '关岛' },
  { value: 'GW', label: '几内亚比绍' },
  { value: 'GY', label: '圭亚那' },
  { value: 'HK', label: '香港' },
  { value: 'HM', label: '赫德岛和麦克唐纳岛' },
  { value: 'HN', label: '洪都拉斯' },
  { value: 'HR', label: '克罗地亚' },
  { value: 'HT', label: '海地' },
  { value: 'HU', label: '匈牙利' },
  { value: 'ID', label: '印度尼西亚' },
  { value: 'IE', label: '爱尔兰' },
  { value: 'IL', label: '以色列' },
  { value: 'IM', label: '曼岛' },
  { value: 'IN', label: '印度' },
  { value: 'IO', label: '英属印度洋领土' },
  { value: 'IQ', label: '伊拉克' },
  { value: 'IR', label: '伊朗' },
  { value: 'IS', label: '冰岛' },
  { value: 'IT', label: '意大利' },
  { value: 'JE', label: '泽西岛' },
  { value: 'JM', label: '牙买加' },
  { value: 'JO', label: '约旦' },
  { value: 'JP', label: '日本' },
  { value: 'KE', label: '肯尼亚' },
  { value: 'KG', label: '吉尔吉斯斯坦' },
  { value: 'KH', label: '柬埔寨' },
  { value: 'KI', label: '基里巴斯' },
  { value: 'KM', label: '科摩罗' },
  { value: 'KN', label: '圣基茨和尼维斯' },
  { value: 'KP', label: '朝鲜' },
  { value: 'KR', label: '韩国' },
  { value: 'KW', label: '科威特' },
  { value: 'KY', label: '开曼群岛' },
  { value: 'KZ', label: '哈萨克斯坦' },
  { value: 'LA', label: '老挝' },
  { value: 'LB', label: '黎巴嫩' },
  { value: 'LC', label: '圣卢西亚' },
  { value: 'LI', label: '列支敦士登' },
  { value: 'LK', label: '斯里兰卡' },
  { value: 'LR', label: '利比里亚' },
  { value: 'LS', label: '莱索托' },
  { value: 'LT', label: '立陶宛' },
  { value: 'LU', label: '卢森堡' },
  { value: 'LV', label: '拉脱维亚' },
  { value: 'LY', label: '利比亚' },
  { value: 'MA', label: '摩洛哥' },
  { value: 'MC', label: '摩纳哥' },
  { value: 'MD', label: '摩尔多瓦' },
  { value: 'ME', label: '黑山' },
  { value: 'MF', label: '圣马丁' },
  { value: 'MG', label: '马达加斯加' },
  { value: 'MH', label: '马绍尔群岛' },
  { value: 'MK', label: '北马其顿' },
  { value: 'ML', label: '马里' },
  { value: 'MM', label: '缅甸' },
  { value: 'MN', label: '蒙古' },
  { value: 'MO', label: '澳门' },
  { value: 'MP', label: '北马里亚纳群岛' },
  { value: 'MQ', label: '马提尼克' },
  { value: 'MR', label: '毛里塔尼亚' },
  { value: 'MS', label: '蒙特塞拉特' },
  { value: 'MT', label: '马耳他' },
  { value: 'MU', label: '毛里求斯' },
  { value: 'MV', label: '马尔代夫' },
  { value: 'MW', label: '马拉维' },
  { value: 'MX', label: '墨西哥' },
  { value: 'MY', label: '马来西亚' },
  { value: 'MZ', label: '莫桑比克' },
  { value: 'NA', label: '纳米比亚' },
  { value: 'NC', label: '新喀里多尼亚' },
  { value: 'NE', label: '尼日尔' },
  { value: 'NF', label: '诺福克岛' },
  { value: 'NG', label: '尼日利亚' },
  { value: 'NI', label: '尼加拉瓜' },
  { value: 'NL', label: '荷兰' },
  { value: 'NO', label: '挪威' },
  { value: 'NP', label: '尼泊尔' },
  { value: 'NR', label: '瑙鲁' },
  { value: 'NU', label: '纽埃' },
  { value: 'NZ', label: '新西兰' },
  { value: 'OM', label: '阿曼' },
  { value: 'PA', label: '巴拿马' },
  { value: 'PE', label: '秘鲁' },
  { value: 'PF', label: '法属波利尼西亚' },
  { value: 'PG', label: '巴布亚新几内亚' },
  { value: 'PH', label: '菲律宾' },
  { value: 'PK', label: '巴基斯坦' },
  { value: 'PL', label: '波兰' },
  { value: 'PM', label: '圣皮埃尔和密克隆' },
  { value: 'PN', label: '皮特凯恩群岛' },
  { value: 'PR', label: '波多黎各' },
  { value: 'PS', label: '巴勒斯坦' },
  { value: 'PT', label: '葡萄牙' },
  { value: 'PW', label: '帕劳' },
  { value: 'PY', label: '巴拉圭' },
  { value: 'QA', label: '卡塔尔' },
  { value: 'RE', label: '留尼汪' },
  { value: 'RO', label: '罗马尼亚' },
  { value: 'RS', label: '塞尔维亚' },
  { value: 'RU', label: '俄罗斯' },
  { value: 'RW', label: '卢旺达' },
  { value: 'SA', label: '沙特阿拉伯' },
  { value: 'SB', label: '所罗门群岛' },
  { value: 'SC', label: '塞舌尔' },
  { value: 'SD', label: '苏丹' },
  { value: 'SE', label: '瑞典' },
  { value: 'SG', label: '新加坡' },
  { value: 'SH', label: '圣赫勒拿' },
  { value: 'SI', label: '斯洛文尼亚' },
  { value: 'SJ', label: '斯瓦尔巴和扬马延' },
  { value: 'SK', label: '斯洛伐克' },
  { value: 'SL', label: '塞拉利昂' },
  { value: 'SM', label: '圣马力诺' },
  { value: 'SN', label: '塞内加尔' },
  { value: 'SO', label: '索马里' },
  { value: 'SR', label: '苏里南' },
  { value: 'SS', label: '南苏丹' },
  { value: 'ST', label: '圣多美和普林西比' },
  { value: 'SV', label: '萨尔瓦多' },
  { value: 'SX', label: '荷属圣马丁' },
  { value: 'SY', label: '叙利亚' },
  { value: 'SZ', label: '斯威士兰' },
  { value: 'TC', label: '特克斯和凯科斯群岛' },
  { value: 'TD', label: '乍得' },
  { value: 'TF', label: '法属南部领地' },
  { value: 'TG', label: '多哥' },
  { value: 'TH', label: '泰国' },
  { value: 'TJ', label: '塔吉克斯坦' },
  { value: 'TK', label: '托克劳' },
  { value: 'TL', label: '东帝汶' },
  { value: 'TM', label: '土库曼斯坦' },
  { value: 'TN', label: '突尼斯' },
  { value: 'TO', label: '汤加' },
  { value: 'TR', label: '土耳其' },
  { value: 'TT', label: '特立尼达和多巴哥' },
  { value: 'TV', label: '图瓦卢' },
  { value: 'TW', label: '台湾' },
  { value: 'TZ', label: '坦桑尼亚' },
  { value: 'UA', label: '乌克兰' },
  { value: 'UG', label: '乌干达' },
  { value: 'UM', label: '美属外岛' },
  { value: 'US', label: '美国' },
  { value: 'UY', label: '乌拉圭' },
  { value: 'UZ', label: '乌兹别克斯坦' },
  { value: 'VA', label: '梵蒂冈' },
  { value: 'VC', label: '圣文森特和格林纳丁斯' },
  { value: 'VE', label: '委内瑞拉' },
  { value: 'VG', label: '英属维尔京群岛' },
  { value: 'VI', label: '美属维尔京群岛' },
  { value: 'VN', label: '越南' },
  { value: 'VU', label: '瓦努阿图' },
  { value: 'WF', label: '瓦利斯和富图纳' },
  { value: 'WS', label: '萨摩亚' },
  { value: 'YE', label: '也门' },
  { value: 'YT', label: '马约特' },
  { value: 'ZA', label: '南非' },
  { value: 'ZM', label: '赞比亚' },
  { value: 'ZW', label: '津巴布韦' },
];

/**
 * 上架状态选项
 */
export const shelfStatusOptions = [
  { value: 'GA', label: 'GA 在架' },
  { value: 'GP', label: 'GP 在架' },
  { value: 'BOTH', label: '均在架' },
];

/**
 * 结算方式选项
 */
export const settlementMethodOptions = [
  { value: 'CPS', label: 'CPS' },
  { value: 'CPA', label: 'CPA' },
  { value: 'CPE', label: 'CPE' },
  { value: 'CPP', label: 'CPP' },
];
